swagger: "2.0"
info:
  title: mobile API
  description: |
    mobile has every tool to get any job done, so codename for the new mobile APIs.
  contact:
    email: astaxie@gmail.com
basePath: /v1
paths:
  /captcha/get:
    get:
      tags:
      - captcha
      description: |-
        Get captcha
        <br>
      responses:
        "200":
          description: '{interface} interface'
  /captcha/verify:
    post:
      tags:
      - captcha
      description: |-
        verify captcha
        <br>
      parameters:
      - in: body
        name: data
        description: verify captcha
        required: true
        schema:
          $ref: '#/definitions/models.Captcha'
      responses:
        "200":
          description: '{bool} bool'
  /user/add:
    post:
      tags:
      - user
      description: |-
        新增事件
        <br>
      parameters:
      - in: body
        name: data
        description: 添加用户
        required: true
        schema:
          $ref: '#/definitions/models.UserAdd'
      responses:
        "200":
          description: '{int} models.User.Id'
  /user/delete/{uid}:
    delete:
      tags:
      - user
      description: |-
        批量删除事件
        <br>
      parameters:
      - in: path
        name: uid
        description: 用户id
        required: true
        type: string
      responses:
        "200":
          description: '{string} string "{"success":true,"data":{},"msg":"批量删除成功"}"'
  /user/list:
    get:
      tags:
      - user
      description: |-
        Get all user list
        <br>
  /user/update:
    put:
      tags:
      - user
      description: |-
        更新事件
        <br>
      parameters:
      - in: body
        name: data
        description: 更新用户
        required: true
        schema:
          $ref: '#/definitions/models.UserUpdate'
      responses:
        "200":
          description: '{string} string "{"success":true,"data":{},"msg":"更新成功"}"'
definitions:
  models.Captcha:
    title: Captcha
    type: object
    properties:
      B64s:
        type: string
      ID:
        type: string
  models.UserAdd:
    title: UserAdd
    type: object
    properties:
      name:
        type: string
      pwd:
        type: string
  models.UserUpdate:
    title: UserUpdate
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      pwd:
        type: string
